# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://nellshamrell.github.io/
baseurl: /
title: Nell Shamrell-Harrington
author: Nell Shamrell-Harrington
description: Personal site and blog
avatar: profile.png
email: nellshamrell@gmail.com
github: nellshamrell
twitter: nellshamrell
linkedin: nellshamrell
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
#disqus: username
#google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
